# Generated by Django 3.1.6 on 2021-02-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GetReddit_Subreddit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_author', models.CharField(max_length=32)),
                ('reddit_title', models.CharField(max_length=32)),
                ('reddit_url', models.CharField(default='', max_length=100)),
                ('reddit_name', models.CharField(max_length=32)),
                ('reddit_upvotes', models.CharField(max_length=6)),
                ('reddit_no_of_comments', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GetReddit_UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=32)),
                ('account_id', models.CharField(max_length=32)),
                ('account_img_link', models.CharField(max_length=128)),
                ('account_comment_karma', models.CharField(max_length=32)),
                ('account_link_karma', models.CharField(max_length=32)),
                ('account_is_mod', models.CharField(max_length=32)),
                ('account_is_gold', models.CharField(max_length=32)),
            ],
        ),
    ]
